// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDClQlzmnqaod-s1lbcnqSbt2PNEuoU09I',
    appId: '1:616267950314:web:2ac34772bf9b7d6797cf93',
    messagingSenderId: '616267950314',
    projectId: 'chat-app-e3f21',
    authDomain: 'chat-app-e3f21.firebaseapp.com',
    storageBucket: 'chat-app-e3f21.firebasestorage.app',
    measurementId: 'G-9XY9PKZB1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM2mb5oU405vsbWveAELcR5lBrlTSFskg',
    appId: '1:616267950314:android:9fc7fa8fd88d09a797cf93',
    messagingSenderId: '616267950314',
    projectId: 'chat-app-e3f21',
    storageBucket: 'chat-app-e3f21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaVCob-azT3tInXsJbuQHob-SgCs9uMvg',
    appId: '1:616267950314:ios:aff89235bc81584a97cf93',
    messagingSenderId: '616267950314',
    projectId: 'chat-app-e3f21',
    storageBucket: 'chat-app-e3f21.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaVCob-azT3tInXsJbuQHob-SgCs9uMvg',
    appId: '1:616267950314:ios:aff89235bc81584a97cf93',
    messagingSenderId: '616267950314',
    projectId: 'chat-app-e3f21',
    storageBucket: 'chat-app-e3f21.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDClQlzmnqaod-s1lbcnqSbt2PNEuoU09I',
    appId: '1:616267950314:web:9cd5f004b252deec97cf93',
    messagingSenderId: '616267950314',
    projectId: 'chat-app-e3f21',
    authDomain: 'chat-app-e3f21.firebaseapp.com',
    storageBucket: 'chat-app-e3f21.firebasestorage.app',
    measurementId: 'G-M4HWYXERGG',
  );

}